# Copyright © 2026 The µcad authors <info@ucad.xyz>
# SPDX-License-Identifier: AGPL-3.0-or-later

[book]
language = "en"
src = "src"

[output.html]
no-section-label = true

[output.html.fold]
enable = true # whether or not to enable section folding
level = 2     # the depth to start folding
