[package]
name = "microcad-viewer"
description = "Âµcad Viewer"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.100"
bevy = "0.16"
bevy_render = "0.16.1"
bevy_mod_outline = "0.10.3"
clap = { version = "4.5.48", features = ["derive"] }
cgmath = { version = "0.18", features = ["serde"] }
crossbeam = "0.8"
dirs = "6"
env_logger = "0.11"
geo = "0.31"
log = "0.4"
notify = "8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
wkt = "0.14"

microcad-lang = { workspace = true }
microcad-core = { workspace = true }
microcad-builtin = { workspace = true }
