# Copyright © 2025-2026 The µcad authors <info@microcad.xyz>
# SPDX-License-Identifier: AGPL-3.0-or-later

[book]
authors = ["Patrick Hoffmann"]
language = "en"
src = "src"
title = "µcad tutorials"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
