# Copyright © 2025 The µcad authors <info@ucad.xyz>
# SPDX-License-Identifier: AGPL-3.0-or-later

[book]
authors = ["Patrick Hoffmann", "Michael Winkelmann"]
language = "en"
src = "src"
title = "The µcad Road Map"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
